#国际化指定文件
spring:
  messages:
    ##message.propertiesi是默认的国际化配置文件，不需要特别指定路径
    basename: i18n.login

  ##禁用thymeleaf的缓存
  thymeleaf:
    cache: false

  ##日期格式转换，默认日期格式xxxx/xx/xx这种
  mvc:
    date-format: yyyy-MM-dd

#指定容器端口
server:
  port: 8082
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /